# traffic-split.yaml
# This manifest is for a conceptual demo, as described in the main README.md.
# It demonstrates how Linkerd splits traffic between two different versions of a service.

apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: my-app-split
spec:
  # This is the "parent" service. All user traffic is directed to this service's name.
  # For example: http://my-app-parent-service/
  service: my-app-parent-service

  # 'backends' defines where the traffic gets split.
  backends:
    # First destination
  - service: my-service-v1 # The name of the Kubernetes Service for v1
    weight: 90 # Send 90% of traffic here

    # Second destination (the "canary")
  - service: my-service-v2 # The name of the Kubernetes Service for v2
    weight: 10 # Send 10% of traffic here
